# Generated by Django 5.1.3 on 2025-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='text_box',
            field=models.TextField(blank=True, null=True),
        ),
    ]
