# Generated by Django 5.1.3 on 2025-02-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
