# Generated by Django 5.1.3 on 2025-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='least_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='mid_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='most_important',
            field=models.BooleanField(default=False),
        ),
    ]
