# Generated by Django 5.1.3 on 2025-01-31 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0002_calendar_event_time_calendar_text_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='SchoolManager.calendar')),
            ],
        ),
    ]
