# Generated by Django 5.1.3 on 2025-02-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0002_event_delete_dayoftheweek_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_pic', models.ImageField(blank=True, null=True, upload_to='doll_pictures')),
                ('Name', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=30)),
                ('Line', models.CharField(max_length=20)),
                ('Release_year', models.IntegerField()),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
    ]
