# Generated by Django 5.1.3 on 2025-02-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0002_event_least_important_event_mid_important_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='least_important',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mid_important',
        ),
    ]
