# Generated by Django 5.1.3 on 2025-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0002_alter_td_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
