# Generated by Django 5.1.3 on 2025-02-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0003_rename_day_calendar_date_remove_calendar_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
