# Generated by Django 5.1.3 on 2025-02-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0003_remove_event_least_important_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-Important']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='most_important',
            new_name='Important',
        ),
    ]
