# Generated by Django 5.1.3 on 2025-02-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0003_remove_event_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
