# Generated by Django 5.1.3 on 2025-02-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0003_rename_day_calendar_date_remove_calendar_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='text_box',
        ),
    ]
