# Generated by Django 5.1.3 on 2025-02-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0003_doll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doll',
        ),
    ]
