# Generated by Django 5.1.3 on 2025-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0004_delete_doll'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='[Event Name]', max_length=100),
        ),
    ]
