# Generated by Django 5.1.3 on 2025-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-_1', '-mid_important', '-least_important']},
        ),
        migrations.AddField(
            model_name='task',
            name='_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='least_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='mid_important',
            field=models.BooleanField(default=False),
        ),
    ]
