# Generated by Django 5.1.3 on 2025-02-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0004_event_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='counter',
        ),
    ]
