# Generated by Django 5.1.3 on 2025-02-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0004_remove_calendar_day_number_remove_calendar_text_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
