# Generated by Django 5.1.3 on 2025-02-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0004_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-Important', '-mid_important', '-least_important']},
        ),
        migrations.AddField(
            model_name='event',
            name='least_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='mid_important',
            field=models.BooleanField(default=False),
        ),
    ]
