# Generated by Django 5.1.3 on 2025-02-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0005_alter_event_options_event_least_important_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='Important',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='least_important',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mid_important',
        ),
    ]
