# Generated by Django 5.1.3 on 2025-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0005_rename_calendar_event_day_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
