# Generated by Django 5.1.3 on 2025-02-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0005_alter_task_options_task__1_task_least_important_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-Important', '-mid_important', '-least_important']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_1',
            new_name='Important',
        ),
    ]
