# Generated by Django 5.1.3 on 2025-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0006_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
