# Generated by Django 5.1.3 on 2025-02-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0006_alter_event_options_remove_event_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
