# Generated by Django 5.1.3 on 2025-02-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0007_alter_event_date_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
