# Generated by Django 5.1.3 on 2025-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0008_alter_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-Important', '-mid_important', '-least_important']},
        ),
        migrations.AddField(
            model_name='event',
            name='Important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='[Event Name]', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='least_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='mid_important',
            field=models.BooleanField(default=False),
        ),
    ]
