# Generated by Django 5.1.3 on 2025-02-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0010_alter_event_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
