# Generated by Django 5.1.3 on 2025-02-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0011_alter_event_date_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_of_event',
        ),
        migrations.AddField(
            model_name='event',
            name='End_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
