# Generated by Django 5.1.3 on 2025-02-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0012_remove_event_date_of_event_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='End_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
