# Generated by Django 5.1.3 on 2025-02-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0013_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='Important',
        ),
        migrations.RemoveField(
            model_name='event',
            name='least_important',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mid_important',
        ),
    ]
