# Generated by Django 5.1.3 on 2025-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0014_alter_event_options_remove_event_important_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='del_ete',
            field=models.BooleanField(default=False),
        ),
    ]
