# Generated by Django 5.1.3 on 2025-02-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManager', '0019_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='del_ete',
        ),
    ]
